<?php

namespace ArvPayolutionApi\Request\Transaction\Analysis;

/**
 * Class CriterionNames
 */
class CriterionNames
{
    const PAYOLUTION_PRE_CHECK = 'PAYOLUTION_PRE_CHECK';

    const PAYOLUTION_CUSTOMER_LANGUAGE = 'PAYOLUTION_CUSTOMER_LANGUAGE';

    const PAYOLUTION_CUSTOMER_REGISTRATION_LEVEL = 'PAYOLUTION_CUSTOMER_REGISTRATION_LEVEL';
    const PAYOLUTION_CUSTOMER_REGISTRATION_DATE = 'PAYOLUTION_CUSTOMER_REGISTRATION_DATE';

    const PAYOLUTION_TAX_AMOUNT = 'PAYOLUTION_TAX_AMOUNT';

    const PAYOLUTION_REQUEST_SYSTEM_VENDOR = 'PAYOLUTION_REQUEST_SYSTEM_VENDOR';
    const PAYOLUTION_REQUEST_SYSTEM_VERSION = 'PAYOLUTION_REQUEST_SYSTEM_VERSION';
    const PAYOLUTION_REQUEST_SYSTEM_TYPE = 'PAYOLUTION_REQUEST_SYSTEM_TYPE';
    const PAYOLUTION_WEBSHOP_URL = 'PAYOLUTION_WEBSHOP_URL';

    const PAYOLUTION_MODULE_NAME = 'PAYOLUTION_MODULE_NAME';
    const PAYOLUTION_MODULE_VERSION = 'PAYOLUTION_MODULE_VERSION';

    const PAYOLUTION_ITEM_DESCR = 'PAYOLUTION_ITEM_DESCR';
    const PAYOLUTION_ITEM_PRICE = 'PAYOLUTION_ITEM_PRICE';
    const PAYOLUTION_ITEM_TAX = 'PAYOLUTION_ITEM_TAX';

    const PAYOLUTION_CUSTOMER_NUMBER = 'PAYOLUTION_CUSTOMER_NUMBER';
    const PAYOLUTION_CUSTOMER_GROUP = 'PAYOLUTION_CUSTOMER_GROUP';

    const PAYOLUTION_SHIPPING_GIVEN = 'PAYOLUTION_SHIPPING_GIVEN';
    const PAYOLUTION_SHIPPING_FAMILY = 'PAYOLUTION_SHIPPING_FAMILY';
    const PAYOLUTION_SHIPPING_COUNTRY = 'PAYOLUTION_SHIPPING_COUNTRY';
    const PAYOLUTION_SHIPPING_CITY = 'PAYOLUTION_SHIPPING_CITY';
    const PAYOLUTION_SHIPPING_ZIP = 'PAYOLUTION_SHIPPING_ZIP';
    const PAYOLUTION_SHIPPING_STREET = 'PAYOLUTION_SHIPPING_STREET';
    const PAYOLUTION_SHIPPING_COMPANY = 'PAYOLUTION_SHIPPING_COMPANY';
    const PAYOLUTION_SHIPPING_TYPE = 'PAYOLUTION_SHIPPING_TYPE';

    const PAYOLUTION_SHIPPING_TYPE_EQUALS_BILLING_ADDRESS = 'EQUALS_BILLING_ADDRESS';
    const PAYOLUTION_SHIPPING_TYPE_ALTERNATIVE_SHIPPING_ADDRESS = 'ALTERNATIVE_SHIPPING_ADDRESS';
    const PAYOLUTION_SHIPPING_TYPE_BRANCH_PICKUP = 'BRANCH_PICKUP';
    const PAYOLUTION_SHIPPING_TYPE_POST_OFFICE_PICKUP = 'POST_OFFICE_PICKUP';
    const PAYOLUTION_SHIPPING_TYPE_PACK_STATION = 'PACK_STATION';

    const PAYOLUTION_ACCOUNT_HOLDER = 'PAYOLUTION_ACCOUNT_HOLDER';
    const PAYOLUTION_ACCOUNT_COUNTRY = 'PAYOLUTION_ACCOUNT_COUNTRY';
    const PAYOLUTION_ACCOUNT_BIC = 'PAYOLUTION_ACCOUNT_BIC';
    const PAYOLUTION_ACCOUNT_IBAN = 'PAYOLUTION_ACCOUNT_IBAN';

    const PAYOLUTION_CALCULATION_ID = 'PAYOLUTION_CALCULATION_ID';
    const PAYOLUTION_INSTALLMENT_AMOUNT = 'PAYOLUTION_INSTALLMENT_AMOUNT';
    const PAYOLUTION_DURATION = 'PAYOLUTION_DURATION';

    const PAYOLUTION_INVOICE_ID = 'PAYOLUTION_INVOICE_ID';

    const PAYOLUTION_ORDER_ID = 'PAYOLUTION_ORDER_ID';

    const PAYOLUTION_TRANSPORTATION_TRACKING = 'PAYOLUTION_TRANSPORTATION_TRACKING';
    const PAYOLUTION_TRANSPORTATION_RETURN_TRACKING = 'PAYOLUTION_TRANSPORTATION_RETURN_TRACKING';
    const PAYOLUTION_TRANSPORTATION_COMPANY = 'PAYOLUTION_TRANSPORTATION_COMPANY';

    const PAYOLUTION_PRE_CHECK_ID = 'PAYOLUTION_PRE_CHECK_ID';

    const PAYOLUTION_CALCULATION_TARGET_COUNTRY = 'PAYOLUTION_CALCULATION_TARGET_COUNTRY';
    /**
     * B2B relevant fields
     */
    const PAYOLUTION_TRX_TYPE = 'PAYOLUTION_TRX_TYPE';
    const PAYOLUTION_COMPANY_NAME = 'PAYOLUTION_COMPANY_NAME';
    const PAYOLUTION_COMPANY_VAT_ID = 'PAYOLUTION_COMPANY_UID';
    const PAYOLUTION_COMPANY_TYPE = 'PAYOLUTION_COMPANY_TYPE';
    const PAYOLUTION_COMPANY_NO = 'PAYOLUTION_COMPANY_TRADEREGISTRY_NUMBER';
    const PAYOLUTION_COMPANY_OWNER_FAMILY = 'PAYOLUTION_COMPANY_OWNER_FAMILY';
    const PAYOLUTION_COMPANY_OWNER_GIVEN = 'PAYOLUTION_COMPANY_OWNER_GIVEN';
    const PAYOLUTION_COMPANY_OWNER_BIRTHDATE = 'PAYOLUTION_COMPANY_OWNER_BIRTHDATE';
}
